import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white dark:bg-black">
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <body className="sfpro antialiased">
          <Navbar />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
